import { createContext, useContext, useState, type ReactNode } from 'react';

const translations = {
  UA: {
    'checkout.name': "Ім'я",
    'checkout.phone': 'Телефон',
    'checkout.address': 'Адреса',
    'checkout.items': 'Товари',
    'checkout.delivery': 'Доставка',
    'checkout.free': 'Безкоштовно',
    'checkout.total': 'Всього',
    'checkout.submit': 'Замовити',
    'checkout.placeholder.name': "Ваше ім'я",
    'checkout.placeholder.phone': '+38 (0XX) XXX-XX-XX',
    'checkout.placeholder.address': 'Місто, вулиця, дім',
    'cart.title': 'Кошик',
    'cart.empty': 'Кошик порожній',
    'cart.continue': 'Продовжити покупки',
    'cart.summary': 'Замовлення',
    'cart.subtotal': 'Сума',
    'cart.shipping': 'Доставка',
    'cart.shipping.calc': 'Розраховується',
    'cart.total': 'Всього',
    'cart.checkout': 'Оформити замовлення',
    'order.title': 'Замовлення підтверджено',
    'order.message': 'Дякуємо! Ми зв\'яжемося з вами найближчим часом.',
    'order.number': 'Номер',
    'order.amount': 'Сума',
    'order.included': 'Включено',
    'order.free': 'Безкоштовно',
    'order.charged': 'Списано з карти',
    'order.continue': 'Продовжити',
    'product.notfound': 'Товар не знайдено',
    'product.back': 'Назад',
    'product.color': 'Колір',
    'product.size': 'Розмір',
    'product.add': 'В кошик',
    'product.added': '✓ В кошику',
    'profile.title': 'Профіль',
    'profile.admin': 'Адмін',
    'profile.panel': 'Панель керування',
    'profile.support': 'Підтримка',
    'profile.write': 'Написати нам',
    'store.tag': 'Магазин',
    'store.hero.tag': 'Нова колекція',
    'store.hero.button': 'ДИВИТИСЯ',
    'store.categories.title': 'Категорії',
    'store.categories.all': 'Всі',
    'store.products.title': 'Товари',
    'store.products.all': 'Всі',
    'products.title': 'Товари',
    'products.count': 'товарів',
    'products.sort.default': 'За замовчуванням',
    'products.sort.price.asc': 'Ціна: від низької',
    'products.sort.price.desc': 'Ціна: від високої',
    'products.sort.name.asc': 'Назва: А-Я',
    'products.sort.name.desc': 'Назва: Я-А',
    'admin.title': 'Панель керування',
    'admin.products': 'Товари',
    'admin.offers': 'Акції',
    'admin.active': 'активні',
    'admin.add.product': 'Додати товар',
    'admin.add.offer': 'Додати акцію',
    'admin.product.name': 'Назва товару',
    'admin.product.category': 'Категорія',
    'admin.product.price': 'Ціна',
    'admin.product.photo': 'Фото товару',
    'admin.product.photo.placeholder': 'Виберіть файл або введіть URL',
    'admin.product.description': 'Опис',
    'admin.product.add': 'Додати товар',
    'admin.offer.title': 'Назва акції',
    'admin.offer.description': 'Опис',
    'admin.offer.discount': 'Знижка %',
    'admin.offer.code': 'Код',
    'admin.offer.add': 'Додати акцію',
    'admin.offer.active': 'Активна',
    'admin.offer.inactive': 'Неактивна',
    'admin.photos.title': 'Фото',
    'admin.photos.hint': 'Натисніть, щоб змінити фото товару',
    'admin.photos.available': 'Доступні фото',
    'admin.photos.tap': 'Натисніть, щоб змінити',
    'admin.dashboard': 'Огляд',
    'admin.access.denied': 'Доступ заборонено',
    'cart.size': 'Розмір',
    'lang.ua': 'Українська',
    'lang.ru': 'Русский',
    'settings.lang': 'Мова',
    'categories.All': 'Всі',
    'categories.Outerwear': 'Верхній одяг',
    'categories.Accessories': 'Аксесуари',
    'categories.Tops': 'Верх',
    'categories.Bottoms': 'Низ',
    'categories.Dresses': 'Сукні',
    'categories.Premium Outerwear': 'Преміум верхній одяг',
    'categories.General': 'Загальне',
    'cart.item.one': 'товар',
    'cart.item.few': 'товари',
    'cart.item.many': 'товарів',
    'product.negotiate': 'Запропонувати ціну',
    'product.negotiate.title': 'Запропонуйте свою ціну',
    'product.negotiate.subtitle': 'Напишіть суму, яку ви готові заплатити, і ми обговоримо',
    'product.negotiate.placeholder': 'Ваша ціна',
    'product.negotiate.send': 'Надіслати пропозицію',
    'admin.collection': 'Колекція',
    'admin.collection.title': 'Назва колекції',
    'admin.collection.subtitle': 'Підзаголовок',
    'admin.collection.tag': 'Тег',
    'admin.collection.save': 'Зберегти',
  },
  RU: {
    'checkout.name': 'Имя',
    'checkout.phone': 'Телефон',
    'checkout.address': 'Адрес',
    'checkout.items': 'Товары',
    'checkout.delivery': 'Доставка',
    'checkout.free': 'Бесплатно',
    'checkout.total': 'Итого',
    'checkout.submit': 'Заказать',
    'checkout.placeholder.name': 'Ваше имя',
    'checkout.placeholder.phone': '+38 (0XX) XXX-XX-XX',
    'checkout.placeholder.address': 'Город, улица, дом',
    'cart.title': 'Корзина',
    'cart.empty': 'Корзина пуста',
    'cart.continue': 'Продолжить покупки',
    'cart.summary': 'Заказ',
    'cart.subtotal': 'Сумма',
    'cart.shipping': 'Доставка',
    'cart.shipping.calc': 'Рассчитывается',
    'cart.total': 'Итого',
    'cart.checkout': 'Оформить заказ',
    'order.title': 'Заказ подтвержден',
    'order.message': 'Спасибо! Мы свяжемся с вами в ближайшее время.',
    'order.number': 'Номер',
    'order.amount': 'Сумма',
    'order.included': 'Включено',
    'order.free': 'Бесплатно',
    'order.charged': 'Списано с карты',
    'order.continue': 'Продолжить',
    'product.notfound': 'Товар не найден',
    'product.back': 'Назад',
    'product.color': 'Цвет',
    'product.size': 'Размер',
    'product.add': 'В корзину',
    'product.added': '✓ В корзине',
    'profile.title': 'Профиль',
    'profile.admin': 'Админ',
    'profile.panel': 'Панель управления',
    'profile.support': 'Поддержка',
    'profile.write': 'Написать нам',
    'store.tag': 'Магазин',
    'store.hero.tag': 'Новая коллекция',
    'store.hero.button': 'СМОТРЕТЬ',
    'store.categories.title': 'Категории',
    'store.categories.all': 'Все',
    'store.products.title': 'Товары',
    'store.products.all': 'Все',
    'products.title': 'Товары',
    'products.count': 'товаров',
    'products.sort.default': 'По умолчанию',
    'products.sort.price.asc': 'Цена: по возрастанию',
    'products.sort.price.desc': 'Цена: по убыванию',
    'products.sort.name.asc': 'Название: А-Я',
    'products.sort.name.desc': 'Название: Я-А',
    'admin.title': 'Панель управления',
    'admin.products': 'Товары',
    'admin.offers': 'Акции',
    'admin.active': 'активны',
    'admin.add.product': 'Добавить товар',
    'admin.add.offer': 'Добавить акцию',
    'admin.product.name': 'Название товара',
    'admin.product.category': 'Категория',
    'admin.product.price': 'Цена',
    'admin.product.photo': 'Фото товара',
    'admin.product.photo.placeholder': 'Выберите файл или введите URL',
    'admin.product.description': 'Описание',
    'admin.product.add': 'Добавить товар',
    'admin.offer.title': 'Название акции',
    'admin.offer.description': 'Описание',
    'admin.offer.discount': 'Скидка %',
    'admin.offer.code': 'Код',
    'admin.offer.add': 'Добавить акцию',
    'admin.offer.active': 'Активна',
    'admin.offer.inactive': 'Неактивна',
    'admin.photos.title': 'Фото',
    'admin.photos.hint': 'Нажмите, чтобы сменить фото товара',
    'admin.photos.available': 'Доступные фото',
    'admin.photos.tap': 'Нажмите, чтобы сменить',
    'admin.dashboard': 'Обзор',
    'admin.access.denied': 'Доступ запрещен',
    'cart.size': 'Размер',
    'lang.ua': 'Українська',
    'lang.ru': 'Русский',
    'settings.lang': 'Язык',
    'categories.All': 'Все',
    'categories.Outerwear': 'Верхняя одежда',
    'categories.Accessories': 'Аксессуары',
    'categories.Tops': 'Верх',
    'categories.Bottoms': 'Низ',
    'categories.Dresses': 'Платья',
    'categories.Premium Outerwear': 'Премиум верхняя одежда',
    'categories.General': 'Общее',
    'cart.item.one': 'товар',
    'cart.item.few': 'товара',
    'cart.item.many': 'товаров',
    'product.negotiate': 'Предложить цену',
    'product.negotiate.title': 'Предложите свою цену',
    'product.negotiate.subtitle': 'Напишите сумму, которую вы готовы заплатить, и мы обсудим',
    'product.negotiate.placeholder': 'Ваша цена',
    'product.negotiate.send': 'Отправить предложение',
    'admin.collection': 'Коллекция',
    'admin.collection.title': 'Название коллекции',
    'admin.collection.subtitle': 'Подзаголовок',
    'admin.collection.tag': 'Тег',
    'admin.collection.save': 'Сохранить',
  },
};

type Lang = keyof typeof translations;

interface LangContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  plural: (n: number, one: string, few: string, many: string) => string;
}

const LangContext = createContext<LangContextValue | null>(null);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('UA');

  const t = (key: string): string => {
    return (translations[lang] as Record<string, string>)[key] || key;
  };

  const plural = (n: number, one: string, few: string, many: string): string => {
    if (lang === 'UA') {
      if (n === 1) return one;
      if (n >= 2 && n <= 4) return few;
      return many;
    }
    return many;
  };

  return <LangContext.Provider value={{ lang, setLang, t, plural }}>{children}</LangContext.Provider>;
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used within LangProvider');
  return ctx;
}
